name: Rob Cates
favicon: null
layout_spectrum: 0.36689
typography_spectrum: 0.887
title: Robert Cates
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#191919'
    - '#434343'
    - '#bcbcbc'
    - '#737373'
    - '#e8e8e8'
  brandStrength: 0.8125
  lightness: 0.21675308141857386
  saturation: 0.8676946102641523
  rhythmicContrast: 0.37879968294873834
purpose: []
