name: Rob Cates
favicon: null
layout_spectrum: 0.7433468091767281
typography_spectrum: 0.9956052401103079
title: Rob Cates
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.6271606825757772
  lightness: 0.21675308141857386
  saturation: 0.8676946102641523
  rhythmicContrast: 0.37879968294873834
purpose: []
