typography_spectrum: 0.8361146973911673
content_rating:
  adult: false
color:
  saturation: 0.16740249446593225
  brandStrength: 0.20701915305107832
  rhythmicContrast: 0.22253961022943258
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  lightness: 0.7283607970457524
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8273854302242398
analytics:
  twitter: null
  google: null
  facebook: null
logo: null
name: Robert Cates
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: About
    id: 3a931c72-2398-4b21-aabb-148398c12661
    type: content
  - name: Services
    id: c1b65395-9c81-4726-9c05-775fdd8e7fa8
    type: content
  - name: Contact
    id: c235732c-8d11-4128-bae1-ebdc554897c5
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Robert Cates
description: 'Singer-Songwriter, Vocal Coach, Worship Leader'
purpose: []
