typography_spectrum: 0.887
content_rating:
  adult: false
color:
  brandColors:
    - '#191919'
    - '#434343'
    - '#bcbcbc'
    - '#737373'
    - '#e8e8e8'
  brandStrength: 0.75
  lightness: 0.25
  saturation: 0.8125
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.36689
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/03387bf6-9b4a-4594-b551-42b81688fde7.png
name: Robert Cates
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About
    id: 3a931c72-2398-4b21-aabb-148398c12661
    type: content
  - name: Services
    id: c1b65395-9c81-4726-9c05-775fdd8e7fa8
    type: content
  - name: Contact
    id: c235732c-8d11-4128-bae1-ebdc554897c5
    type: content
favicon: null
title: 'Singer-songwriter, Vocal Coach, Worship Leader'
description: 'Singer-Songwriter, Vocal Coach, Worship Leader'
purpose: []
