title: 'Singer-songwriter, Vocal Coach, Worship Leader'
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: 'Singer-Songwriter, Vocal Coach, Worship Leader'
color:
  saturation: 0.8125
  brandStrength: 0.75
  rhythmicContrast: 0.75
  brandColors:
    - '#191919'
    - '#434343'
    - '#bcbcbc'
    - '#737373'
    - '#e8e8e8'
  lightness: 0.25
navigation:
  - name: About
    id: 3a931c72-2398-4b21-aabb-148398c12661
    type: content
  - name: Services
    id: c1b65395-9c81-4726-9c05-775fdd8e7fa8
    type: content
  - name: Contact
    id: c235732c-8d11-4128-bae1-ebdc554897c5
    type: content
cta:
  bucket: null
  version: null
  domain: null
name: Robert Cates
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/03387bf6-9b4a-4594-b551-42b81688fde7.png
typography_spectrum: 0.5085106
layout_spectrum: 0.1531915
content_rating:
  adult: false
