typography_spectrum: 0.887
color:
  brandColors:
    - '#191919'
    - '#434343'
    - '#bcbcbc'
    - '#737373'
    - '#e8e8e8'
  brandStrength: 0.75
  lightness: 0.25
  saturation: 0.8125
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.36689
analytics:
  google: null
  facebook: null
  twitter: null
name: Robert Cates
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Robert Cates
description: 'Singer-Songwriter, Vocal Coach, Worship Leader'
purpose: []
